dataset_str:
  "ETH3DWAI(
    resolution=${dataset.eth3d_wai.one_sample_test.dataset_resolution},
    principal_point_centered=${dataset.eth3d_wai.one_sample_test.principal_point_centered},
    seed=${dataset.eth3d_wai.one_sample_test.seed},
    transform='${dataset.eth3d_wai.one_sample_test.transform}',
    data_norm_type='${dataset.eth3d_wai.one_sample_test.data_norm_type}',
    ROOT='${dataset.eth3d_wai.one_sample_test.ROOT}',
    dataset_metadata_dir='${dataset.eth3d_wai.one_sample_test.dataset_metadata_dir}',
    variable_num_views=${dataset.eth3d_wai.one_sample_test.variable_num_views},
    num_views=${dataset.eth3d_wai.one_sample_test.num_views},
    covisibility_thres=${dataset.eth3d_wai.one_sample_test.covisibility_thres},
    sample_specific_scene=${dataset.eth3d_wai.one_sample_test.sample_specific_scene},
    specific_scene_name='${dataset.eth3d_wai.one_sample_test.specific_scene_name}')"
dataset_resolution: ${dataset.resolution_one_sample_test_eth3d}
principal_point_centered: ${dataset.principal_point_centered}
seed: 777
transform: 'imgnorm'
data_norm_type: ${model.data_norm_type}
ROOT: ${root_data_dir}/eth3d_WAI
dataset_metadata_dir: ${mapanything_dataset_metadata_dir}
variable_num_views: ${dataset.test.variable_num_views}
num_views: ${dataset.num_views}
covisibility_thres: 0.025
sample_specific_scene: true
specific_scene_name: ${specific_scene_name}
